Add more resources about colors
component-driven/awesome-list pull request #5
Opened 2019-01-30 16:26 UTC by okonet

2019-01-30 20:06 UTC, sapegin requested changes
Thanks!

2019-01-30 20:06 UTC, sapegin commented on Readme.md
> +- https://github.com/lyft/coloralgorithm
Could you add a description for this one?

2019-01-31 13:30 UTC, sapegin commented
And a link as a link, and not a URL ;-/

2019-01-31 13:50 UTC, okonet commented
I think GitHub is going to convert it to link automatically

2019-01-31 13:51 UTC, okonet commented
![2019-01-31 at 14 50](https://user-images.githubusercontent.com/11071/52058382-9ac56e00-2567-11e9-869c-3cae105d6793.png)

2019-01-31 14:00 UTC, sapegin commented
It's a clickable URL and it's ugly. You've just spent more time making this screenshot, than fixing would take ;-/

2019-01-31 15:09 UTC, okonet commented
I've changed it

2019-02-01 10:59 UTC, merged